version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: mern_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/teamdb
    depends_on:
      - mongo
    volumes:
      - backend-data:/app/data
    networks:
      default:
        aliases:
          - backend-service

  frontend:
    build: ./frontend
    container_name: mern_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
  backend-data:
